version: '3.3'

services:
    nginx:
        image: nginx
        ports:
            - ${WEB_PORT}:80
        links:
            - fpm
        volumes:
            - ${HOST_APP_PATH}:${CONTAINER_APP_PATH}
            - ./conf:/etc/nginx/conf.d
    fpm:
        image: php:7.1-fpm
        volumes:
            - ${HOST_APP_PATH}:${CONTAINER_APP_PATH}
        links:
            - mysql
    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - ${DB_PORT}:3306
        volumes:
            - ./databases:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASS}
            - MYSQL_DATABASE=${DB_NAME}
    adminer:
        image: adminer
        restart: always
        ports:
            - ${ADMINER_PORT}:8080

